CREATE TABLE cliente (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255) NOT NULL,
   phone BIGINT,
   customer_code BIGINT NOT NULL,
   customer_type VARCHAR(255),
   customer_registered VARCHAR(255),
   CONSTRAINT pk_cliente PRIMARY KEY (id)
);