CREATE TABLE cliente (
  customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255) NOT NULL,
   phone VARCHAR(255),
   customer_code BIGINT NOT NULL,
   customer_type VARCHAR(255),
   customer_registered VARCHAR(255),
   CONSTRAINT pk_cliente PRIMARY KEY (customer_id)
);

ALTER TABLE cliente ADD CONSTRAINT uc_cliente_customer_code UNIQUE (customer_code);