CREATE TABLE carregamento (
  load_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   load_number BIGINT,
   driver VARCHAR(255) NOT NULL,
   departure_date date NOT NULL,
   CONSTRAINT pk_carregamento PRIMARY KEY (load_id)
);