CREATE TABLE vendedores (
  seller_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   sellers_name VARCHAR(255) NOT NULL,
   sellersrca BIGINT NOT NULL,
   CONSTRAINT pk_vendedores PRIMARY KEY (seller_id)
);