CREATE TABLE vendedores (
  seller_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   sellers_name VARCHAR(255) NOT NULL,
   sellers_rca BIGINT NOT NULL,
   CONSTRAINT pk_vendedores PRIMARY KEY (seller_id)
);
ALTER TABLE vendedores ADD CONSTRAINT uc_vendedores_sellers_rca UNIQUE (sellers_rca);