CREATE TABLE pedido (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   order_code BIGINT NOT NULL,
   customer_code BIGINT,
   load_number BIGINT,
   name VARCHAR(255) NOT NULL,
   order_type VARCHAR(255),
   status VARCHAR(255),
   purchase_date date NOT NULL,
   invoicing_date date NOT NULL,
   seller_id BIGINT,
   days_until_delivery INT NOT NULL,
   order_future_del_state VARCHAR(255),
   CONSTRAINT pk_pedido PRIMARY KEY (id)
);

ALTER TABLE pedido ADD CONSTRAINT uc_pedido_order_code UNIQUE (order_code);

ALTER TABLE pedido ADD CONSTRAINT FK_PEDIDO_ON_CUSTOMERCODE FOREIGN KEY (customer_code) REFERENCES cliente (id);

ALTER TABLE pedido ADD CONSTRAINT FK_PEDIDO_ON_LOADNUMBER FOREIGN KEY (load_number) REFERENCES carregamento (loadid);

ALTER TABLE pedido ADD CONSTRAINT FK_PEDIDO_ON_SELLERID FOREIGN KEY (seller_id) REFERENCES vendedores (seller_id);