CREATE TABLE pedido (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   order_number VARCHAR(255) NOT NULL,
   customer_code BIGINT,
   load_number BIGINT,
   order_type VARCHAR(255),
   status VARCHAR(255),
   purchase_date date NOT NULL,
   invoicing_date date NOT NULL,
   seller_id BIGINT,
   CONSTRAINT pk_pedido PRIMARY KEY (id)
);

ALTER TABLE pedido ADD CONSTRAINT uc_pedido_order_number UNIQUE (order_number);

ALTER TABLE pedido ADD CONSTRAINT FK_PEDIDO_ON_CUSTOMERCODE FOREIGN KEY (customer_code) REFERENCES cliente (id);

ALTER TABLE pedido ADD CONSTRAINT FK_PEDIDO_ON_LOADNUMBER FOREIGN KEY (load_number) REFERENCES carregamento (loadid);

ALTER TABLE pedido ADD CONSTRAINT FK_PEDIDO_ON_SELLERID FOREIGN KEY (seller_id) REFERENCES vendedores (seller_id);