CREATE TABLE situacao (
  state_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   order_id BIGINT,
   state VARCHAR(255),
   first_level VARCHAR(255),
   second_level VARCHAR(255),
   description VARCHAR(255),
   solve_date date,
   solve_driver VARCHAR(255),
   days_until_solve INT,
   resolve VARCHAR(255),
   CONSTRAINT pk_situacao PRIMARY KEY (state_id)
);

ALTER TABLE situacao ADD CONSTRAINT uc_situacao_order UNIQUE (order_id);

ALTER TABLE situacao ADD CONSTRAINT FK_SITUACAO_ON_ORDER FOREIGN KEY (order_id) REFERENCES pedido (id);