CREATE TABLE "ENTREGA FUTURA" (
  id UUID NOT NULL,
   customer_id BIGINT,
   order_id BIGINT,
   order_state VARCHAR(255),
   days_until_delivery INT NOT NULL,
   CONSTRAINT pk_entrega_futura PRIMARY KEY (id)
);

ALTER TABLE "ENTREGA FUTURA" ADD CONSTRAINT FK_ENTREGA_FUTURA_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES cliente (id);

ALTER TABLE "ENTREGA FUTURA" ADD CONSTRAINT FK_ENTREGA_FUTURA_ON_ORDER FOREIGN KEY (order_id) REFERENCES pedido (id);