CREATE TABLE situacao (
  state_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   id BIGINT,
   order_number VARCHAR(255) NOT NULL,
   state VARCHAR(255),
   first_level VARCHAR(255),
   second_level VARCHAR(255),
   description VARCHAR(255),
   solve_date date,
   solve_driver VARCHAR(255),
   days_until_solve BIGINT,
   CONSTRAINT pk_situacao PRIMARY KEY (state_id)
);

ALTER TABLE situacao ADD CONSTRAINT FK_SITUACAO_ON_ID FOREIGN KEY (id) REFERENCES pedido (id);