package moderna.home.deliverycontrolsystem.enumerators

enum class FirstLevel {

    ENDERECO_INFORMADO_DIVERGENTE,
    CLIENTE_OU_RESPONSAVEL_AUSENTE,
    MATERIAL_ERRADO,
    MATERIAL_COM_AVARIA_PARCIAL,
    MATERIAL_TOTALMENTE_AVARIADO,
    FORA_DO_HORARIO_DE_ENTREGA,
    NAO_CONSEGUIU_CONTATO_COM_O_CLIENTE,
    MATERIAL_FORA_DA_DATA_SOLICITADA_PELO_CLIENTE,
    FALTA_DE_MERCADORIA,
    LOCAL_REMOTO,
    LOCAL_DE_DIFICIL_ACESSO,
    ERRO_DE_VENDA,
    ERRO_DE_SEPARACAO,
    ERRO_DE_SEPARACAO_E_VENDA,
    ERRO_DE_ENTREGA,
    ERRO_DE_VENDA_E_ENTREGA,
    NOTA_PERDIDA,
    SEM_PENDENCIA,
    NOTA_SEM_ASSINATURA,

}