package moderna.home.deliverycontrolsystem.enumerators

enum class SecondLevel {
    ERRO_NA_SEPARACAO_DO_MATERIAL,
    ERRO_NO_PEDIDO,
    ENDERECO_FORNECIDO_NA_NOTA_ERRADO,
    AUSENCIA_DE_NUMERO_DE_CONTATO,
    NUMERO_DE_CONTATO_FORNECIDO_NA_NOTA_ERRADO,
    DATA_NAO_INFORMADA_NA_NOTA,
    DATA_INFORMADA_NA_NOTA,
    ERRO_DE_ROTA,
    NAO_APLICAVEL,
    ERRO_DE_VENDA_E_SEPARACAO,
    ERRO_DE_ENTREGA,
    AVARIA_NAO_IDENTIFICADA_NA_SEPARACAO,
    ERRO_DE_VENDA,
    NOTA_PERDIDA_NA_ENTREGA,
    FURO_DE_ESTOQUE,
    SEM_PENDENCIA,
    NOTA_NAO_ASSINADA,
}